-- Generated by drizzle-kit, then fixed by hand before commit: the rebuilds no longer copy the new
-- columns from the old tables (SQLite would read "speed" as a string), and the DESC index
-- expressions are unquoted as in 0000. New columns take their defaults: Standard runs, real spend.
CREATE TABLE `provider_batches` (
	`id` text PRIMARY KEY NOT NULL,
	`job_set_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`model_id` text NOT NULL,
	`remote_id` text,
	`display_name` text NOT NULL,
	`state` text DEFAULT 'submitting' NOT NULL,
	`handle` text,
	`item_count` integer NOT NULL,
	`credential_hint` text,
	`submitted_at` text,
	`expires_at` text,
	`last_polled_at` text,
	`next_poll_at` text,
	`finished_at` text,
	`notified_at` text,
	`cleaned_at` text,
	`error_code` text,
	`error_message` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`job_set_id`) REFERENCES `job_sets`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`provider_id`) REFERENCES `providers`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "provider_batches_state_check" CHECK(state IN ('submitting','queued','running','succeeded','failed','canceled','expired'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `provider_batches_job_set_id_unique` ON `provider_batches` (`job_set_id`);--> statement-breakpoint
CREATE INDEX `idx_provider_batches_active` ON `provider_batches` (`state`,`next_poll_at`) WHERE state IN ('submitting','queued','running');--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_job_sets` (
	`id` text PRIMARY KEY NOT NULL,
	`idempotency_key` text,
	`op` text NOT NULL,
	`modality` text DEFAULT 'image' NOT NULL,
	`provider_id` text NOT NULL,
	`model_id` text NOT NULL,
	`prompt` text DEFAULT '' NOT NULL,
	`prompt_original` text,
	`negative_prompt` text,
	`request_json` text NOT NULL,
	`batch_size` integer DEFAULT 1 NOT NULL,
	`priority` integer DEFAULT 10 NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`source` text DEFAULT 'composer' NOT NULL,
	`canvas_id` text,
	`canvas_node_id` text,
	`canvas_run_id` text,
	`cost_estimate_usd` real,
	`cost_actual_usd` real,
	`error_code` text,
	`error_message` text,
	`created_at` text NOT NULL,
	`started_at` text,
	`finished_at` text,
	`speed` text DEFAULT 'standard' NOT NULL,
	FOREIGN KEY (`provider_id`) REFERENCES `providers`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`canvas_id`) REFERENCES `canvases`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`canvas_run_id`) REFERENCES `canvas_runs`(`id`) ON UPDATE no action ON DELETE set null,
	CONSTRAINT "job_sets_op_check" CHECK(op IN ('generate','edit','inpaint','outpaint','variation','upscale','remove_bg','text_edit','relight','angles','enhance','decompose','crop','grade','overlay')),
	CONSTRAINT "job_sets_batch_size_check" CHECK(batch_size BETWEEN 1 AND 4),
	CONSTRAINT "job_sets_status_check" CHECK(status IN ('pending','submitting','queued','running','succeeded','failed','canceled','interrupted','partial')),
	CONSTRAINT "job_sets_source_check" CHECK(source IN ('composer','detail_editor','canvas','api','recreate')),
	CONSTRAINT "job_sets_speed_check" CHECK(speed IN ('standard','flex','priority','batch'))
);
--> statement-breakpoint
INSERT INTO `__new_job_sets`("id", "idempotency_key", "op", "modality", "provider_id", "model_id", "prompt", "prompt_original", "negative_prompt", "request_json", "batch_size", "priority", "status", "source", "canvas_id", "canvas_node_id", "canvas_run_id", "cost_estimate_usd", "cost_actual_usd", "error_code", "error_message", "created_at", "started_at", "finished_at") SELECT "id", "idempotency_key", "op", "modality", "provider_id", "model_id", "prompt", "prompt_original", "negative_prompt", "request_json", "batch_size", "priority", "status", "source", "canvas_id", "canvas_node_id", "canvas_run_id", "cost_estimate_usd", "cost_actual_usd", "error_code", "error_message", "created_at", "started_at", "finished_at" FROM `job_sets`;--> statement-breakpoint
DROP TABLE `job_sets`;--> statement-breakpoint
ALTER TABLE `__new_job_sets` RENAME TO `job_sets`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `job_sets_idempotency_key_unique` ON `job_sets` (`idempotency_key`);--> statement-breakpoint
CREATE INDEX `idx_job_sets_created` ON `job_sets` (created_at DESC);--> statement-breakpoint
CREATE INDEX `idx_job_sets_sched` ON `job_sets` (priority DESC,`created_at`) WHERE status IN ('pending','submitting','queued','running');--> statement-breakpoint
CREATE INDEX `idx_job_sets_canvas` ON `job_sets` (`canvas_id`,`canvas_node_id`);--> statement-breakpoint
CREATE INDEX `idx_job_sets_run` ON `job_sets` (`canvas_run_id`);--> statement-breakpoint
CREATE TABLE `__new_jobs` (
	`id` text PRIMARY KEY NOT NULL,
	`job_set_id` text NOT NULL,
	`idx` integer NOT NULL,
	`provider_job_id` text,
	`idempotency_key` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`progress` real,
	`seed` integer,
	`attempt` integer DEFAULT 0 NOT NULL,
	`next_attempt_at` text,
	`error_code` text,
	`error_message` text,
	`latency_ms` integer,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	`started_at` text,
	`finished_at` text,
	`error_reason` text,
	`speed_used` text,
	FOREIGN KEY (`job_set_id`) REFERENCES `job_sets`(`id`) ON UPDATE no action ON DELETE cascade,
	CONSTRAINT "jobs_status_check" CHECK(status IN ('pending','submitting','queued','running','succeeded','failed','canceled','interrupted')),
	CONSTRAINT "jobs_speed_used_check" CHECK(speed_used IN ('standard','flex','priority','batch'))
);
--> statement-breakpoint
INSERT INTO `__new_jobs`("id", "job_set_id", "idx", "provider_job_id", "idempotency_key", "status", "progress", "seed", "attempt", "next_attempt_at", "error_code", "error_message", "latency_ms", "created_at", "updated_at", "started_at", "finished_at", "error_reason") SELECT "id", "job_set_id", "idx", "provider_job_id", "idempotency_key", "status", "progress", "seed", "attempt", "next_attempt_at", "error_code", "error_message", "latency_ms", "created_at", "updated_at", "started_at", "finished_at", "error_reason" FROM `jobs`;--> statement-breakpoint
DROP TABLE `jobs`;--> statement-breakpoint
ALTER TABLE `__new_jobs` RENAME TO `jobs`;--> statement-breakpoint
CREATE INDEX `idx_jobs_active` ON `jobs` (`status`,`next_attempt_at`) WHERE status IN ('pending','submitting','queued','running');--> statement-breakpoint
CREATE INDEX `idx_jobs_job_set` ON `jobs` (`job_set_id`,`idx`);--> statement-breakpoint
CREATE UNIQUE INDEX `jobs_job_set_id_idx_unique` ON `jobs` (`job_set_id`,`idx`);--> statement-breakpoint
ALTER TABLE `models` ADD `speeds` text;--> statement-breakpoint
ALTER TABLE `providers` ADD `settings` text;--> statement-breakpoint
CREATE TABLE `__new_usage_log` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`ts` text NOT NULL,
	`provider_id` text NOT NULL,
	`model_id` text NOT NULL,
	`job_set_id` text,
	`job_id` text,
	`batch_index` integer,
	`operation` text NOT NULL,
	`outcome` text NOT NULL,
	`size` text,
	`quality` text,
	`units` text,
	`estimate_min` real,
	`estimate_max` real,
	`cost_usd` real,
	`cost_source` text,
	`price_as_of` text,
	`discarded` integer DEFAULT 0 NOT NULL,
	`latency_ms` integer,
	`http_status` integer,
	`speed` text,
	`simulated` integer DEFAULT 0 NOT NULL,
	CONSTRAINT "usage_log_outcome_check" CHECK(outcome IN ('succeeded','failed','canceled')),
	CONSTRAINT "usage_log_cost_source_check" CHECK(cost_source IN ('reconciled','estimated','unknown')),
	CONSTRAINT "usage_log_speed_check" CHECK(speed IN ('standard','flex','priority','batch'))
);
--> statement-breakpoint
INSERT INTO `__new_usage_log`("id", "ts", "provider_id", "model_id", "job_set_id", "job_id", "batch_index", "operation", "outcome", "size", "quality", "units", "estimate_min", "estimate_max", "cost_usd", "cost_source", "price_as_of", "discarded", "latency_ms", "http_status") SELECT "id", "ts", "provider_id", "model_id", "job_set_id", "job_id", "batch_index", "operation", "outcome", "size", "quality", "units", "estimate_min", "estimate_max", "cost_usd", "cost_source", "price_as_of", "discarded", "latency_ms", "http_status" FROM `usage_log`;--> statement-breakpoint
DROP TABLE `usage_log`;--> statement-breakpoint
ALTER TABLE `__new_usage_log` RENAME TO `usage_log`;--> statement-breakpoint
CREATE INDEX `idx_usage_ts` ON `usage_log` (ts DESC);--> statement-breakpoint
CREATE INDEX `idx_usage_model` ON `usage_log` (`provider_id`,`model_id`,ts DESC);